version: '3.8'

services:
  redis:
    image: "redis:alpine"
    container_name: redis_container
    ports:
      - "6379:6379"

  flask_app:
    build: .
    container_name: pathfindr
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    env_file:
      - properties.env
    volumes:
      - .:/app

